# Generated by Django 2.2 on 2020-09-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('published', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'rss_news',
            },
        ),
    ]
